/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import models.ModeloProducto;

/**
 *
 * @author josec
 */
public class PedidoProductoComponent extends javax.swing.JPanel {

    private ModeloProducto producto;
    private int cantidad = 0;
    private ModifyOrderListener listener;

    public PedidoProductoComponent(ModeloProducto producto, ModifyOrderListener listener) {
        initComponents();
        this.producto = producto;
        productoLabel.setText(producto.getNombre());
        precioLabel.setText("Bs. " + producto.getPrecio());
        this.listener = listener;
    }
    /**
     * Creates new form PedidoProductoComponent
     */
    public PedidoProductoComponent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productoLabel = new javax.swing.JLabel();
        cantidadLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        precioLabel = new javax.swing.JLabel();

        productoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productoLabel.setText("Nombre del Producto");

        cantidadLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantidadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadLabel.setText("0");

        addButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addButton.setText("+");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        removeButton.setText("-");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        precioLabel.setText("Bs. Precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(productoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precioLabel)
                .addGap(27, 27, 27)
                .addComponent(removeButton)
                .addGap(18, 18, 18)
                .addComponent(cantidadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productoLabel)
                    .addComponent(cantidadLabel)
                    .addComponent(addButton)
                    .addComponent(precioLabel)
                    .addComponent(removeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        cantidad++;
        cantidadLabel.setText(String.valueOf(cantidad));
        listener.onOrderModified(producto.getCodigo(), cantidad);
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if (cantidad > 0) {
            cantidad--;
            listener.onOrderModified(producto.getCodigo(), cantidad);
        }
        cantidadLabel.setText(String.valueOf(cantidad));
    }//GEN-LAST:event_removeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JLabel productoLabel;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
