/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import models.Cafeteria;

/**
 *
 * @author josec
 */
public class WinMenu extends javax.swing.JFrame {

    private Cafeteria cafeteria;

    public WinMenu(Cafeteria cafeteria) {
        this.cafeteria = cafeteria;
        initComponents();
    }
    
    
    
    /**
     * Creates new form WinMenu
     */
    public WinMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoPedidoButton = new javax.swing.JButton();
        adminProductosButton = new javax.swing.JButton();
        summaryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevoPedidoButton.setText("Nuevo Pedido");
        nuevoPedidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoPedidoButtonActionPerformed(evt);
            }
        });

        adminProductosButton.setText("Administrar Productos");
        adminProductosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminProductosButtonActionPerformed(evt);
            }
        });

        summaryButton.setText("Mostrar resumen de Pedidos");
        summaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nuevoPedidoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminProductosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(summaryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(adminProductosButton)
                .addGap(18, 18, 18)
                .addComponent(nuevoPedidoButton)
                .addGap(18, 18, 18)
                .addComponent(summaryButton)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoPedidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoPedidoButtonActionPerformed
        cafeteria.iniciarPedido();
        WinPedido ventanaPedido = new WinPedido(cafeteria, this);
        ventanaPedido.setVisible(true);
    }//GEN-LAST:event_nuevoPedidoButtonActionPerformed

    private void adminProductosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminProductosButtonActionPerformed
        
        WinProducto ventanaProducto = new WinProducto(cafeteria, this);
        ventanaProducto.setVisible(true);
        
        
    }//GEN-LAST:event_adminProductosButtonActionPerformed

    private void summaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryButtonActionPerformed
        int cantidadPedidos = cafeteria.getCantidadPedidosRealizados();
        double montoTotal = cafeteria.getMontoTotalPedidosRealizados();

        String mensaje = "Cantidad de pedidos realizados: " + cantidadPedidos + "\n" +
                         "Monto total de pedidos realizados: Bs. " + montoTotal;

        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Resumen de Pedidos", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_summaryButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminProductosButton;
    private javax.swing.JButton nuevoPedidoButton;
    private javax.swing.JButton summaryButton;
    // End of variables declaration//GEN-END:variables
}
